'use client'

import { useState } from 'react'
import { useQuery } from '@tanstack/react-query'
import { motion } from 'framer-motion'
import { AlertTriangle, Check, Copy, Loader2, QrCode } from 'lucide-react'
import toast from 'react-hot-toast'

/**
 * The user's own USDC receiving address, with a QR code.
 *
 * This is the "just send money" path: no form, no transaction hash to paste.
 * The address is derived per user, so an arriving transfer is attributed by
 * destination and credited by the chain webhook without the user telling us
 * anything. Everything shown here comes from the server - the QR is rendered
 * server-side as SVG, so the browser never re-encodes the address and cannot
 * display one that differs from what we are watching.
 */

interface DepositAddressResponse {
    address: string
    uri: string
    qrSvg: string
    network: string
    chainId: number
    asset: string
    tokenContract: string
    autoCrediting: boolean
    linkedWallets: Array<{ address: string; verified: boolean; isPrimary: boolean }>
}

function shorten(address: string): string {
    return `${address.slice(0, 6)}…${address.slice(-4)}`
}

export function DepositAddressCard() {
    const [copied, setCopied] = useState(false)

    const query = useQuery<DepositAddressResponse>({
        queryKey: ['wallet', 'deposit-address'],
        queryFn: async () => {
            const response = await fetch('/api/wallet/deposit-address')
            const payload = await response.json().catch(() => null)
            if (!response.ok) {
                throw new Error(payload?.error ?? 'Could not load your deposit address')
            }
            return payload as DepositAddressResponse
        },
        // The address is derived and permanent, so there is nothing to refetch.
        staleTime: Infinity,
        retry: false,
    })

    async function copyAddress(address: string) {
        try {
            await navigator.clipboard.writeText(address)
            setCopied(true)
            toast.success('Address copied')
            setTimeout(() => setCopied(false), 2000)
        } catch {
            toast.error('Could not copy - select the address and copy it manually')
        }
    }

    // Bound to a local so the non-null narrowing survives into the callbacks
    // and JSX below; `query.data` on its own widens back inside a closure.
    const data = query.data

    return (
        <motion.div
            initial={{ opacity: 0, y: 12 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.35 }}
            className="rounded-[24px] border border-black/[0.04] bg-white p-5 shadow-[0_4px_24px_rgba(0,0,0,0.02)] dark:border-white/[0.06] dark:bg-[#121214] dark:shadow-none sm:p-6"
        >
            <div className="flex items-start gap-3">
                <span className="flex h-9 w-9 shrink-0 items-center justify-center rounded-full bg-[#f1ebff] text-[#6330cf] dark:bg-[#6330cf]/20 dark:text-[#b79bff]">
                    <QrCode size={16} />
                </span>
                <div className="min-w-0">
                    <h2 className="text-base font-bold tracking-tight text-[#1c1c24] dark:text-white">
                        Deposit USDC
                    </h2>
                    <p className="mt-1 text-xs text-[#81858c]">
                        Scan or copy your personal address. Funds credit automatically once confirmed.
                    </p>
                </div>
            </div>

            {query.isLoading && (
                <p className="flex items-center gap-2 py-10 text-xs text-[#81858c]">
                    <Loader2 size={14} className="animate-spin" />
                    Preparing your deposit address
                </p>
            )}

            {query.isError && (
                <div className="mt-5 rounded-2xl bg-[#fff6e5] px-4 py-3 text-[11.5px] font-semibold leading-relaxed text-[#9a6200] dark:bg-[#3a2d14] dark:text-[#f5c86b]">
                    {(query.error as Error).message}
                </div>
            )}

            {data && (
                <>
                    <div className="mt-5 flex flex-col items-center gap-5 sm:flex-row sm:items-start">
                        {/*
                          The SVG is generated by our own API from the same
                          address string shown below it. Rendering it with
                          dangerouslySetInnerHTML is safe here specifically
                          because the content is server-produced QR markup, not
                          anything a user supplied.
                        */}
                        <div
                            className="h-[168px] w-[168px] shrink-0 rounded-2xl bg-white p-2 [&>svg]:h-full [&>svg]:w-full"
                            dangerouslySetInnerHTML={{ __html: data.qrSvg }}
                        />

                        <div className="min-w-0 flex-1">
                            <p className="text-[10px] font-bold uppercase tracking-wider text-[#777984] dark:text-[#888a93]">
                                Your {data.asset} address · {data.network}
                            </p>
                            <p className="mt-1.5 break-all font-mono text-[12px] font-semibold leading-relaxed text-[#1c1c24] dark:text-[#e4e5eb]">
                                {data.address}
                            </p>

                            <button
                                type="button"
                                onClick={() => copyAddress(data.address)}
                                className="mt-3 inline-flex cursor-pointer items-center gap-1.5 rounded-full bg-gradient-to-r from-[#6330cf] to-[#8553ec] px-4 py-2 text-xs font-bold text-white shadow-md transition-all hover:opacity-95"
                            >
                                {copied ? <Check size={13} /> : <Copy size={13} />}
                                {copied ? 'Copied' : 'Copy address'}
                            </button>

                            {data.linkedWallets.length > 0 && (
                                <p className="mt-3 text-[11.5px] leading-relaxed text-[#81858c]">
                                    You can send from your linked wallet{' '}
                                    <span className="font-semibold">
                                        {shorten(data.linkedWallets[0].address)}
                                    </span>
                                    {data.linkedWallets.length > 1 &&
                                        ` (+${data.linkedWallets.length - 1} more)`}
                                    .
                                </p>
                            )}
                        </div>
                    </div>

                    <div className="mt-5 flex items-start gap-2 rounded-2xl bg-[#fff6e5] px-4 py-3 dark:bg-[#3a2d14]">
                        <AlertTriangle size={14} className="mt-0.5 shrink-0 text-[#9a6200] dark:text-[#f5c86b]" />
                        <p className="text-[11.5px] font-semibold leading-relaxed text-[#9a6200] dark:text-[#f5c86b]">
                            Send only <span className="font-bold">{data.asset}</span> on{' '}
                            <span className="font-bold">{data.network}</span>. Other tokens, or the
                            same token on another network, cannot be recovered.
                        </p>
                    </div>

                    {/*
                      Told plainly rather than hidden: without a chain listener
                      the transfer still arrives on-chain but nothing credits
                      the wallet, and a user staring at an unchanged balance
                      deserves to know that is expected.
                    */}
                    {!data.autoCrediting && (
                        <p className="mt-3 text-[11.5px] leading-relaxed text-[#81858c]">
                            Automatic crediting is not switched on for this environment yet, so a deposit may
                            need to be confirmed manually before it appears.
                        </p>
                    )}
                </>
            )}
        </motion.div>
    )
}
