// Generated by scripts/generate-world-dots.mjs - do not edit by hand.
// Natural Earth land polygons (world-atlas, 110m) sampled on an equirectangular
// grid, packed 8 samples per byte. 2751 of 9600 cells are land.

export const WORLD_DOTS = {
    width: 150,
    height: 64,
    latMax: 84,
    latMin: -69.6000,
    /** Packed land bitmask, most significant bit first. */
    bits: 'AAAAAAB/gP/AAAAAAAAAAAAAAAAAAABx9///wABwDAABwAAAAAAAAACCHn///gAGgAAAAIAAAAAAAAAPt2AP//gAAAAHAB/4A4AAAAABwFrgD/+AAAAAYAf/+wAAAAHAAPxv8D/9AAAYAYb/////4Ag///8i2OB/4AAD/kPv///////d/////4Ph/BYAP+P/////////EP////kFA8AAAe//////////+A/////AYAYAAB8/////////x4ACB///A/gAAABsf///////wGAAIAP//wfgAAAQ8////////AOAAAAX//+/4AABIf////////AMAAAAD//+/4AAAd/////////4IAAAAC///+GAAAP/////////oAAAAAB////CAAAP//ff/////oAAAAAB////AAAAP34e//////IAAAAAB///8AAAB8J5Of////4QAAAAAB///wAAAB4Bv/f///+QQAAAAAA///gAAABwAv/f////IwAAAAAAf//gAAAA/gA/////+DgAAAAAAP/+AAAAB/5g//////EAAAAAAAD/2AAAAB///+/////AAAAAAAAF8BAAAAD//++f///+AAAAAAAAC8BAAAAH//+/if//+AAAAAAAAAcDAAAAP///f8P//4AAAAAAAAAeYQAAAP///P4H4+AAAAAAAAAAPwBAAAP///v4Hw+BAAAAAAAAAA8AAAAP///3gDAPBAAAAAAAAAAEAAAAP///8ADAPhgAAAAAAAAAEOQAAH///7ABADAAAAAAAAAAAD/wAAD////ABgIAwAAAAAAAAAAf4AAB9//+AAgEEAAAAAAAAAAAf/AAAAf/+AAAUMAAAAAAAAAAA//AAAAf/4AAAM8IAAAAAAAAAB//wAAAf/wAAAEdGAAAAAAAAAB//+AAAf/wAAACBD4gAAAAAAAB///AAAP/gAAABAAdQAAAAAAAA///AAAP/gAAAAKA6AAAAAAAAAf//AAAH/wAAAAAAACAAAAAAAAf/+AAAP/xAAAAAHIAAAAAAAAAP/+AAAP/zAAAAAfMAgAAAAAAAH/+AAAP/HAAAAA/8AAAAAAAAAD/8AAAP+GAAAAD/+BAAAAAAAAD/8AAAH/GAAAAP//AAAAAAAAAD/gAAAH+AAAAAP//gAAAAAAAAH/gAAAH+AAAAAH//gAAAAAAAAH/AAAAD8AAAAAH//gAAAAAAAAH+AAAAB4AAAAAHh/gAAAAAAAAH4AAAAAAAAAAAEAfAAAAAAAAAP4AAAAAAAAAAAAAeAAAAAAAAAPgAAAAAAAAAAAAAAACAAAAAAAPAAAAAAAAAAAAAACAMAAAAAAAPAAAAAAAAAAAAAAAAQAAAAAAAOAAAAAAAAAAAAAAAAAAAAAAAAOAAAAAAAAAAAAAAAAAAAAAAAAMIAAAAAAAAAAAAAAAAAAAAAAAOAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAAAAAAgAAAAAAAYAAAIBAAAAAAAAAABAAAAAAAH/w////+AA',
} as const

/** Expands the packed bitmask into one boolean per grid cell. */
export function decodeWorldDots(): boolean[] {
    const binary = typeof atob === 'function' ? atob(WORLD_DOTS.bits) : Buffer.from(WORLD_DOTS.bits, 'base64').toString('binary')
    const total = WORLD_DOTS.width * WORLD_DOTS.height
    const cells: boolean[] = new Array(total)

    for (let index = 0; index < total; index += 1) {
        const byte = binary.charCodeAt(index >> 3)
        cells[index] = (byte & (0x80 >> (index & 7))) !== 0
    }

    return cells
}

/** Longitude/latitude to a 0-1 position on the map, matching the sampling grid. */
export function project(lon: number, lat: number): { x: number; y: number } {
    return {
        x: (lon + 180) / 360,
        y: (WORLD_DOTS.latMax - lat) / (WORLD_DOTS.latMax - WORLD_DOTS.latMin),
    }
}
